version: '3.3'
services:
  blognodejs:
    build:
      context: .
      dockerfile: ./Dockerfileprod
    container_name: nest-docker-postgres
    environment:
      - PORT=${PORT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - blogdb
    volumes:
      - ./app:/src
    expose:
      - "3000"
    networks:
      - blogautonetwork


networks:
  blogautonetwork:
    external: true
