version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Expose HTTP port
      - "443:443"  # Expose HTTPS 
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Bind custom NGINX config
      - ./certs:/etc/nginx/certs            # Mount your SSL certs
    networks:
      - blogautonetwork  # Use the same custom network
networks:
  blogautonetwork:
    external: true  # Use the external network